export const light = {
	title: 'light',
	primary: '#6200EE',
	secondary: '#DDDDDD',
	text: '#000000',
	button: '#BBB',
	challengeIcon: '#6200EE',
	challengeBorder: '#BBB',
	challengeDesktopBorder: 'gold',
	challengeCore: '#03DAC6',
	modal: '#FFFFFFAA',
	headerBackground: '#FFF159',
	toolTip: '#000',
	hamburger: '#000',
	searchBar: '#fff',
	separator: '#AAAAAAAA',
	optionRow: '#f7f7f7',
	smallIcon: '#333',
	mainBg: '#fff',
	storeButton: '#FFF159',
};
